name: Cleanup Old Images

on:
  # schedule:
  #   - cron: '0 23 * * 6' # Every Saturday at 23:00 UTC
  pull_request:

env:
  ECR_REPOSITORY: ruby

jobs:
  cleanup_old_images:
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions

      - name: Install awscli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          rm -f awscliv2.zip
          rm -rf ./aws

      - name: Cleanup old images
        run: |
          # [TEST_MODE] 20 month ago: 2025-08-01 -> 2023-12-01]
          month_ago=`date -d "20 month ago" +%Y-%m-%d`
          aws ecr-public describe-images --region us-east-1 --repository-name ${{ env.ECR_REPOSITORY }} --max-items 2 --output json \
            --query "imageDetails[?imagePushedAt<=\`${month_ago}\`]" \
            | jq '.[] | select(.imageTags == null or (.imageTags | length == 0))'
          images=`aws ecr-public describe-images --region us-east-1 --repository-name ${{ env.ECR_REPOSITORY }} --max-items 2 --output json \
            --query "imageDetails[?imagePushedAt<=\`${month_ago}\`]" \
            | jq '.[] | select(.imageTags == null or (.imageTags | length == 0))'
            | jq -r '.imageDigest'`
          for image in $images; do
            echo "[DRY_RUN]Deleting image: $image"
          done
